INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '15_415_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_416_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_417_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_418_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_419_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_420_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_421_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_422_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_423_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_424_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_425_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_426_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_427_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_428_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_429_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_501_0119_1_3',
            'Provision of Hearing Services by an Audiologist',
            119,
            'Specialised Hearing Services',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_502_0134_1_3',
            'Provision of Hearing Services by an Audiologist',
            134,
            'Hearing Services',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_503_0134_1_3',
            'Provision of Hearing Services by an Audiometrist',
            134,
            'Hearing Services',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_606_0118_1_3',
            'Early Childhood Intervention Professional - Counsellor',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_609_0118_1_3',
            'Early Childhood Intervention Professional - Exercise Physiologist',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        support_category_number = EXCLUDED.support_category_number,
        support_purpose = EXCLUDED.support_purpose;