INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '15_062_0118_1_3',
            'Early Childhood Intervention Professional - Dietitian',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_062_0128_3_3',
            'Assessment Recommendation Therapy or Training - Dietitian',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_200_0126_1_3',
            'Assessment Recommendation Therapy or Training - Exercise Physiologist',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_200_0128_1_3',
            'Assessment Recommendation Therapy or Training - Exercise Physiologist',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_300_0103_1_3',
            'Assistive Technology Mentoring',
            103,
            'Assistive Products For Personal Care And Safety',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_400_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_401_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_402_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_403_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_404_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_405_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_406_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_407_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_408_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_409_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_410_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_411_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_412_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_413_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_414_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        support_category_number = EXCLUDED.support_category_number,
        support_purpose = EXCLUDED.support_purpose;