INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '09_006_0106_6_3',
            'Life Transition Planning Incl. Mentoring Peer-Support And Indiv Skill Develop',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            9,
            'Increased Social and Community Participation',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_008_0116_6_3',
            'Innovative Community Participation',
            116,
            'Innovative Community Participation',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_009_0117_6_3',
            'Skills Development And Training',
            117,
            'Development Of Daily Living And Life Skills',
            9,
            'Increased Social and Community Participation',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_011_0125_6_3',
            'Community Participation Activities',
            125,
            'Participation In Community, Social And Civic Activities',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_590_0106_6_3',
            'Activity Based Transport',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_591_0117_6_3',
            'Activity Based Transport',
            117,
            'Development Of Daily Living And Life Skills',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_799_0106_6_3',
            'Provider travel - non-labour costs',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_799_0117_6_3',
            'Provider travel - non-labour costs',
            117,
            'Development Of Daily Living And Life Skills',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_002_0106_8_3',
            'Support Coordination Level 2: Coordination of Supports',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_011_0128_5_3',
            'Employment Related Assessment, Counselling and Advice  - Other Professional',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_016_0102_5_3',
            'Employment Assistance',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_021_0102_5_3',
            'School Leaver Employment Supports',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_054_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Psychologist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_055_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Physiotherapist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_101_0106_6_3',
            'Psychosocial Recovery Coaching - Weekday Daytime',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_590_0102_5_3',
            'Activity Based Transport',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_590_0133_5_3',
            'Activity Based Transport',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_599_0133_5_3',
            'Centre Capital Cost',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_613_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Developmental Educator',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_617_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Occupational Therapist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        support_category_number = EXCLUDED.support_category_number,
        support_purpose = EXCLUDED.support_purpose;