INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '10_620_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Rehabilitation Counsellor',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_622_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Speech Pathologist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_799_0102_5_3',
            'Provider travel - non-labour costs',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_799_0128_5_3',
            'Provider travel - non-labour costs',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_799_0133_5_3',
            'Provider travel - non-labour costs',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_806_0133_5_1',
            'Supports in Employment - Weekday Daytime',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_022_0110_7_3',
            'Specialist Behavioural Intervention Support',
            110,
            'Specialist Positive Behaviour Support',
            11,
            'Improved Relationships',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_023_0110_7_3',
            'Behaviour Management Plan Including Training in Behaviour Management Strategies',
            110,
            'Specialist Positive Behaviour Support',
            11,
            'Improved Relationships',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_024_0117_7_3',
            'Individual Social Skills Development',
            117,
            'Development Of Daily Living And Life Skills',
            11,
            'Improved Relationships',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_590_0117_7_3',
            'Activity Based Transport',
            117,
            'Development Of Daily Living And Life Skills',
            11,
            'Improved Relationships',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_799_0110_7_3',
            'Provider travel - non-labour costs',
            110,
            'Specialist Positive Behaviour Support',
            11,
            'Improved Relationships',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_799_0117_7_3',
            'Provider travel - non-labour costs',
            117,
            'Development Of Daily Living And Life Skills',
            11,
            'Improved Relationships',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_025_0128_3_3',
            'Advice provided by a Dietitian on managing diet for health and well-being',
            128,
            'Therapeutic Supports',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_027_0126_3_3',
            'Advice provided by an Exercise Physiologist regarding exercise required',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_027_0128_3_3',
            'Advice provided by an Exercise Physiologist regarding exercise required',
            128,
            'Therapeutic Supports',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_029_0126_3_3',
            'Personal training provided by a Personal Trainer to a participant',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_799_0126_3_3',
            'Provider travel - non-labour costs',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            12,
            'Improved Health and Wellbeing',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_799_0128_3_3',
            'Provider travel - non-labour costs',
            128,
            'Therapeutic Supports',
            12,
            'Improved Health and Wellbeing',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '13_030_0102_4_3',
            'Transition Through School And To Further Education',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            13,
            'Improved Learning',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '13_590_0102_4_3',
            'Activity Based Transport',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            13,
            'Improved Learning',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        support_category_number = EXCLUDED.support_category_number,
        support_purpose = EXCLUDED.support_purpose;