INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '05_123612811_0105_1_2',
            'Transfer AT - Pool Environment Hoist',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_123612891_0105_1_2',
            'Transfer AT - Ceiling Hoist',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_123621111_0105_1_2',
            'Transfer AT - Sling Standard',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_123621121_0105_1_2',
            'Transfer AT - Sling Non-Standard',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_150000115_0123_1_2',
            'AT Rental - Assistive Products for Household Tasks',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_150300111_0123_2_2',
            'Assistive products for preparing food and drink',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_150600111_0123_2_2',
            'Assistive products for dishwashing',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_150900111_0123_2_2',
            'Assistive products for eating and drinking',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_151200111_0123_2_2',
            'Assistive products to facilitate house cleaning',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_151600111_0123_2_2',
            'Assistive products to facilitate laundry',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_151800111_0123_2_2',
            'Assistive products to facilitate gardening',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_174_0119_1_2',
            'Hearing Services Program - Adults With High Intensity Needs (AH Only)',
            119,
            'Specialised Hearing Services',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_177_0119_1_2',
            'Hearing Services Program - Child Under 4 Yrs (AH Only)',
            119,
            'Specialised Hearing Services',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_180315111_0103_1_2',
            'Bed - Ancillary Furniture',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_180909811_0103_1_2',
            'Specialised Seating with Sit-Stand Assistance',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_180915811_0103_1_2',
            'Specialised Lounge Chair - Mobile with Pressure Management/PositioningSystems',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_180921821_0103_1_2',
            'Specialised Static Seating with Pressure Management and/or PosturalSupport',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_180939882_0105_1_2',
            'Postural Support - Modular Seating Systems',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_181200711_0103_1_2',
            'Bed - Access/Transfer Pole/Blocks/Rails/Rail-Covers',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_181207811_0103_1_2',
            'Bed - Manually adjusted',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_181210811_0103_1_2',
            'Bed - Electrically adjusted',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_181224811_0103_1_2',
            'Sleep Positioning System and Accessories - Custom Made',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_181800111_0103_2_2',
            'Home Safety -  Slip Resistance Coating/Grab and/or Guide Rails',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_183015811_0103_2_2',
            'Ramp - portable for access needs',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_189900111_0123_2_2',
            'Customisation, adaptions, or upgrade cost to standard household items',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220300115_0113_1_2',
            'AT Rental - Vision support or alternate access',
            113,
            'Vision Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220318811_0113_1_2',
            'Vision - Electronic Video Magnifier',
            113,
            'Vision Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220321811_0113_1_2',
            'Vision - Image Enlargement Software',
            113,
            'Vision Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220600112_0122_1_2',
            'AT Rental - Hearing Devices and Accessories',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220615111_0122_1_2',
            'Hearing device - Standard level',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220615211_0122_1_2',
            'Hearing device - Intermediate level',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220615811_0122_1_2',
            'Hearing device - Advanced level',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220618811_0122_1_2',
            'Hearing device - Non-Standard',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220621811_0122_1_2',
            'Hearing device - External speech processor and accessories',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220625247_0122_1_2',
            'Hearing accessory - Induction Loop',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220627171_0122_1_2',
            'Hearing accessory - Remote Control',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220627232_0122_1_2',
            'Hearing accessory - TV function',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220627271_0122_1_2',
            'Hearing accessory - Music device',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220627811_0122_1_2',
            'Hearing device - Personal Amplifiers/Binaural Listener',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_220906234_0124_1_2',
            'Voice Amplifiers For Personal Use',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_221300111_0124_1_2',
            'Communication and Information AT - Computer/Device Interfaces',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_221315254_0124_1_2',
            'Communication AT - Simple Button or Keys with Voice Output',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_221315811_0124_1_2',
            'Communication - Face to Face - Electronic',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_221315880_0124_1_2',
            'Personal Reader - Speech and/or Visual Output',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_221336811_0113_1_2',
            'Vision - Braille device',
            113,
            'Vision Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_222100111_0124_1_2',
            'Communication AT: Non-Electronic Devices Books or Tools for face to face',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_222100115_0124_1_2',
            'AT Rental - Communication and Computer access',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_222102112_0124_1_2',
            'Adaptive software for a communication or information access disability need',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_222106253_0124_1_2',
            'Communication - Amplifiers',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_222106843_0122_1_2',
            'Hearing accessory - Remote Microphone System',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;