INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '01_002_0107_1_1',
            'Assistance With Self-Care Activities - Standard - Weekday Night',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_003_0107_1_1',
            'Assistance From Live-In Carer',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_004_0107_1_1',
            'Assistance with Personal Domestic Activities',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_010_0107_1_1',
            'Assistance With Self-Care Activities - Night-Time Sleepover',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_011_0107_1_1',
            'Assistance With Self-Care Activities - Standard - Weekday Daytime',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_012_0107_1_1',
            'Assistance With Self-Care Activities - Standard - Public Holiday',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_013_0107_1_1',
            'Assistance With Self-Care Activities - Standard - Saturday',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_014_0107_1_1',
            'Assistance With Self-Care Activities - Standard - Sunday',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_015_0107_1_1',
            'Assistance With Self-Care Activities - Standard - Weekday Evening',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_016_0104_1_1',
            'Specialised Home Based Assistance For A Child',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_017_0107_1_1',
            'On-Call Overnight Monitoring-Off Site or Onsite (Includes 1 hour of assistance)',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_019_0120_1_1',
            'House or Yard Maintenance',
            120,
            'Household Tasks',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_020_0120_1_1',
            'House Cleaning And Other Household Activities',
            120,
            'Household Tasks',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_021_0120_1_1',
            'Linen Service',
            120,
            'Household Tasks',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_023_0120_1_1',
            'Assistance with the cost of the preparation and delivery of meals',
            120,
            'Household Tasks',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_026_0115_1_1',
            'Assistance In Living Arrangements (Host Family/Alternative Family Situation)',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_027_0115_1_1',
            'Assistance In A Shared Living Arrangement',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_045_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:4 - Weekday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_046_0115_1_1',
            'Assistance In Individual Living Arrangement For Person With Complex Needs',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_049_0104_1_1',
            'Establishment Fee For Personal Care/Participation',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_049_0107_1_1',
            'Establishment Fee For Personal Care/Participation',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_050_0115_1_1',
            'Assistance With Daily Life Tasks Provided In Residential Aged Care Facility',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_051_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:4 - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_052_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:4 - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_053_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:4 - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_054_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:2 - Weekday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_055_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:2 - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_056_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:2 - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_057_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:2 - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_058_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:1 - Weekday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_059_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:1 - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_060_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:1 - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_061_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:1 - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_062_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:3 - Weekday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_063_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:3 - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_064_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:3 - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_065_0115_1_1',
            'STA And Assistance (Inc. Respite) - 1:3 - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_066_0115_1_1',
            'Unplanned onsite shared supports in Specialist Disability Accommodation',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'WK',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_082_0115_1_1',
            'Medium Term Accommodation',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'D',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_134_0117_8_1',
            'Capacity Building and Training in Self-Management and Plan Management',
            117,
            'Development Of Daily Living And Life Skills',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_200_0115_1_1',
            'Assistance With Self-Care Activities in a STA - Weekday Daytime',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_201_0115_1_1',
            'Assistance With Self-Care Activities in a STA - Weekday Evening',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_202_0115_1_1',
            'Assistance With Self-Care Activities in a STA - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_203_0115_1_1',
            'Assistance With Self-Care Activities in a STA - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_204_0115_1_1',
            'Assistance With Self-Care Activities in a STA - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_205_0115_1_1',
            'Assistance With Self-Care Activities in a STA - Weekday Night',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_400_0104_1_1',
            'Assistance With Self-Care Activities - High Intensity - Weekday Daytime',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_401_0104_1_1',
            'Assistance With Self-Care Activities - High Intensity - Weekday Evening',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_402_0104_1_1',
            'Assistance With Self-Care Activities - High Intensity - Saturday',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_403_0104_1_1',
            'Assistance With Self-Care Activities - High Intensity - Sunday',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;