INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '05_040609171_0103_1_1',
            'Cyclic Pressure Unit - Replacement Garments and Compression Sleeves',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040609811_0103_1_1',
            'Circulation Support - Air-Filled Garments and Compression Units',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_043006111_0103_1_2',
            'Cooling Vest - All Sizes',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_043303511_0103_1_2',
            'Postural Support - Air Floatation or Automated Pressure Management',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_043303811_0103_1_2',
            'Postural Support - Foam and/or Gel component system',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_043306002_0103_1_2',
            'Pressure Reduction Mattress - Air Filled Section',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_043306803_0103_1_2',
            'Pressure Reduction Mattress or Overlay - Complete',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_043306804_0103_1_2',
            'Pressure Reduction Mattress or Overlay - High Complexity Need',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_044839811_0103_1_2',
            'Standing Frame - Supports for Standing',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_044839870_0103_1_2',
            'Standing or Walking Frame accessory - Powered Component (including Myoelectric)',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_060000115_0135_1_2',
            'AT Rental - Prosthesis and Orthosis',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_060315111_0135_1_2',
            'Orthosis - Cervical and Cranial',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_060318821_0135_1_2',
            'Orthosis - Cervico-Thoraco-Lumbo-Sacral',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_060600111_0135_1_2',
            'Orthosis - Upper Limb - Prefabricated',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_060600821_0135_1_2',
            'Orthosis - Upper Limb - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_060688121_0135_1_2',
            'Orthosis - Dynamic or Lycra - Limb',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061203111_0135_1_2',
            'Orthosis - Foot (all types) or Prefabricated Orthotic Footwear',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061203821_0135_1_2',
            'Orthosis - Footwear/Shoes Other - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061206111_0135_1_2',
            'Orthosis - Ankle Foot (AFO) - Prefabricated',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061206821_0135_1_2',
            'Orthosis - Ankle Foot (AFO) - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061206891_0135_1_2',
            'Orthosis - Ankle Foot with Ankle Joints - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061209111_0105_1_2',
            'Orthosis - Knee - Prefabricated',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061209121_0135_1_2',
            'Orthosis - Knee - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061209821_0135_1_2',
            'Orthosis - Thigh Knee Ankle - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061212821_0135_1_2',
            'Orthosis - Knee Ankle Foot - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061215111_0105_1_2',
            'Orthosis - Hip - Prefabricated',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061218811_0135_1_2',
            'Orthosis - Bilateral Hip Knee Ankle Foot Orthosis (incl RGO) - Prefabricated',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061218821_0135_1_2',
            'Orthosis - Hip Thigh Knee Ankle - Custom Made',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061219821_0135_1_2',
            'Orthosis - Bilateral Thoraco-lumbar/Lumbo-Sacral Hip Knee Ankle Foot - Custom',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061290821_0135_1_2',
            'Orthosis - Dynamic or Lycra - Full Body',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061500811_0135_1_2',
            'Orthosis - Trunk/Lower Body - FES or Powered - to supportstanding/walking',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061800121_0135_1_2',
            'Prosthesis - Upper Limb (Including Powered)',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_061826871_0135_1_2',
            'Prosthesis - Accessory - Arm and Hand for Sport and Leisure',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_062200921_0135_1_2',
            'Prosthesis - Osseo-Integration Mounting (Upper or Lower) - Additional Cost',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_062409121_0135_1_2',
            'Prosthesis - Transtibial or Lower',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_062415121_0135_1_2',
            'Prosthesis - Transfemoral or Higher',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_062488034_0135_1_2',
            'Prosthesis - Lower Limb - Not Defined',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_062488121_0135_1_2',
            'Prosthesis - Specialist Lower Limb For Sports',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_062490191_0135_1_2',
            'Prosthesis - For Wet Area Use (i.e. waterproofing) - Additional Cost',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_063000821_0135_1_2',
            'Prosthesis - Not Limb Related',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_090000155_0103_1_2',
            'AT Rental - Personal Care and Safety',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_091200111_0103_1_2',
            'Toilet Attachments and Accessories - Seat/Toilet Raiser/Toileting Bidet',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_091203053_0103_1_2',
            'Shower Commode - Wheeled - Low Transporter',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_091203811_0103_1_2',
            'Shower Commode - Wheeled',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_091203821_0103_1_2',
            'Shower Commode - Wheeled - High High Intensityity need',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_091203891_0103_1_2',
            'Shower Commode - Wheeled - Tilt In Space',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_093305121_0103_1_2',
            'Bathing Support - Special Design',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_093312811_0103_1_2',
            'Change Table/Shower Trolley - Manual',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_093312891_0103_1_2',
            'Change Table/Shower Trolley - Powered',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_120303111_0105_1_2',
            'Walking Supports - Sticks Canes And Crutches',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;