INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '03_090000911_0103_1_1',
            'Low Cost AT - Personal Care And Safety',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_090348111_0103_1_2',
            'Extra cost for adapted or adapting clothing and/or footwear for disability need',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_090900111_0103_1_2',
            'Assistive products for dressing or undressing',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_091_0121_1_1',
            'Telephone Or Video Interpreting',
            121,
            'Interpreting And Translation',
            3,
            'Consumables',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_091800084_0103_1_1',
            'Continence - bowel care',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_092100082_0103_1_1',
            'Continence - consumables',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_092400080_0103_1_1',
            'Continence - catheters/sheaths',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_092700081_0103_1_1',
            'Continence - drain/leg bags',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_092700083_0103_1_1',
            'Continence - urinary collection items and accessories',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_093021078_0103_1_1',
            'Continence - reusable/washable personal protection',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_093021079_0103_1_1',
            'Continence - disposable personal protection',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_093040085_0103_1_1',
            'Continence - bed/chair/floor protection',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_120000911_0105_1_1',
            'Low Cost AT - Personal Mobility',
            105,
            'Personal Mobility Equipment',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930078_0103_1_1',
            'HEN - pump plus accessory - syringe feed',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930079_0103_1_1',
            'HEN - pump plus accessory - non-syringe feed',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930080_0103_1_1',
            'HEN - bolus syringes',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930081_0103_1_1',
            'HEN - gastrostomy devices',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930082_0103_1_1',
            'Additional Extension Sets For Bolus Feeding - 10/Annual',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930083_0103_1_1',
            'Additional Extension Sets For Pump Feeding - 10/Annual',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930084_0103_1_1',
            'HEN - giving sets',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930085_0103_1_1',
            'HEN - containers',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930086_0103_1_1',
            'Additional Bolus Syringes - 100/Annual',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930087_0103_1_1',
            'HEN - water flush syringes',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_150930088_0103_1_1',
            'HEN - Other equipment',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_220300911_0113_1_1',
            'Low Cost AT - Vision Related AT',
            113,
            'Vision Equipment',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_220600911_0122_1_1',
            'Low Cost AT - Hearing Related AT',
            122,
            'Hearing Equipment',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_222100911_0124_1_1',
            'Low Cost AT - Communication Or Cognitive Support',
            124,
            'Communication And Information Equipment',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_501509092_0103_1_1',
            'Repairs and Maintenance - HEN AT',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_710400002_0103_1_1',
            'Disability-Related Health Equipment and Consumables - Set Up/Training',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_710930080_0103_1_1',
            'Delivery - Personal care Safety and Disability-related HealthConsumables',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_900100156_0130_1_1',
            'Assistance Animal - Dog Guide - Dietary Needs',
            130,
            'Assistance Animals',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_900100157_0130_1_1',
            'Assistance Animal - Dog Guide - Grooming',
            130,
            'Assistance Animals',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_900100158_0130_1_1',
            'Assistance Animal - Dog Guide - Veterinary Services',
            130,
            'Assistance Animals',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_900100159_0130_1_1',
            'Assistance Animal - Dog Guide - Annual Accreditation',
            130,
            'Assistance Animals',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_049_0104_1_1',
            'Establishment Fee For Personal Care/Participation',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_049_0125_1_1',
            'Establishment Fee For Personal Care/Participation',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_049_0133_5_1',
            'Establishment Fee For Personal Care/Participation',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_049_0136_1_1',
            'Establishment Fee For Personal Care/Participation',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_102_0125_6_1',
            'Access Community Social and Rec Activ - Standard - Public Holiday',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_102_0136_6_1',
            'Group Activities - Standard - Weekday Daytime',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_103_0125_6_1',
            'Access Community Social and Rec Activ - Standard - Weekday Evening',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_103_0136_6_1',
            'Group Activities - Standard - Weekday Evening',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_104_0125_6_1',
            'Access Community Social and Rec Activ - Standard - Weekday Daytime',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_104_0136_6_1',
            'Group Activities - Standard - Saturday',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_105_0125_6_1',
            'Access Community Social and Rec Activ - Standard - Saturday',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_105_0136_6_1',
            'Group Activities - Standard - Sunday',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_106_0125_6_1',
            'Access Community Social and Rec Activ - Standard - Sunday',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_106_0136_6_1',
            'Group Activities - Standard - Public Holiday',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_210_0125_6_1',
            'Community Social And Recreational Activities',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_400_0104_1_1',
            'Access Community Social and Rec Activ - High Intensity - Weekday Daytime',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;