INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '08_590_0106_2_3',
            'Activity Based Transport',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            8,
            'Improved Living Arrangements',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '08_799_0106_2_3',
            'Provider travel - non-labour costs',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            8,
            'Improved Living Arrangements',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_006_0106_6_3',
            'Life Transition Planning Incl. Mentoring Peer-Support And Indiv Skill Develop',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            9,
            'Increased Social and Community Participation',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_008_0116_6_3',
            'Innovative Community Participation',
            116,
            'Innovative Community Participation',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_009_0117_6_3',
            'Skills Development And Training',
            117,
            'Development Of Daily Living And Life Skills',
            9,
            'Increased Social and Community Participation',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_011_0125_6_3',
            'Community Participation Activities',
            125,
            'Participation In Community, Social And Civic Activities',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_590_0106_6_3',
            'Activity Based Transport',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_591_0117_6_3',
            'Activity Based Transport',
            117,
            'Development Of Daily Living And Life Skills',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_799_0106_6_3',
            'Provider travel - non-labour costs',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '09_799_0117_6_3',
            'Provider travel - non-labour costs',
            117,
            'Development Of Daily Living And Life Skills',
            9,
            'Increased Social and Community Participation',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_002_0106_8_3',
            'Support Coordination Level 2: Coordination of Supports',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_011_0128_5_3',
            'Employment Related Assessment, Counselling and Advice  - Other Professional',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_016_0102_5_3',
            'Employment Assistance',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_021_0102_5_3',
            'School Leaver Employment Supports',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_054_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Psychologist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_055_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Physiotherapist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_101_0106_6_3',
            'Psychosocial Recovery Coaching - Weekday Daytime',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_590_0102_5_3',
            'Activity Based Transport',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_590_0133_5_3',
            'Activity Based Transport',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_599_0133_5_3',
            'Centre Capital Cost',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_613_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Developmental Educator',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_617_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Occupational Therapist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_620_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Rehabilitation Counsellor',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_622_0128_5_3',
            'Employment Related  Assessment, Counselling and Advice - Speech Pathologist',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_799_0102_5_3',
            'Provider travel - non-labour costs',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_799_0128_5_3',
            'Provider travel - non-labour costs',
            128,
            'Therapeutic Supports',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_799_0133_5_3',
            'Provider travel - non-labour costs',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '10_806_0133_5_1',
            'Supports in Employment - Weekday Daytime',
            133,
            'Specialised Supported Employment',
            10,
            'Finding and Keeping a Job',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_022_0110_7_3',
            'Specialist Behavioural Intervention Support',
            110,
            'Specialist Positive Behaviour Support',
            11,
            'Improved Relationships',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_023_0110_7_3',
            'Behaviour Management Plan Including Training in Behaviour Management Strategies',
            110,
            'Specialist Positive Behaviour Support',
            11,
            'Improved Relationships',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_024_0117_7_3',
            'Individual Social Skills Development',
            117,
            'Development Of Daily Living And Life Skills',
            11,
            'Improved Relationships',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_590_0117_7_3',
            'Activity Based Transport',
            117,
            'Development Of Daily Living And Life Skills',
            11,
            'Improved Relationships',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_799_0110_7_3',
            'Provider travel - non-labour costs',
            110,
            'Specialist Positive Behaviour Support',
            11,
            'Improved Relationships',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '11_799_0117_7_3',
            'Provider travel - non-labour costs',
            117,
            'Development Of Daily Living And Life Skills',
            11,
            'Improved Relationships',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_025_0128_3_3',
            'Advice provided by a Dietitian on managing diet for health and well-being',
            128,
            'Therapeutic Supports',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_027_0126_3_3',
            'Advice provided by an Exercise Physiologist regarding exercise required',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_027_0128_3_3',
            'Advice provided by an Exercise Physiologist regarding exercise required',
            128,
            'Therapeutic Supports',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_029_0126_3_3',
            'Personal training provided by a Personal Trainer to a participant',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            12,
            'Improved Health and Wellbeing',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_799_0126_3_3',
            'Provider travel - non-labour costs',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            12,
            'Improved Health and Wellbeing',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '12_799_0128_3_3',
            'Provider travel - non-labour costs',
            128,
            'Therapeutic Supports',
            12,
            'Improved Health and Wellbeing',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '13_030_0102_4_3',
            'Transition Through School And To Further Education',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            13,
            'Improved Learning',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '13_590_0102_4_3',
            'Activity Based Transport',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            13,
            'Improved Learning',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '13_799_0102_4_3',
            'Provider travel - non-labour costs',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            13,
            'Improved Learning',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '14_034_0127_8_3',
            'Plan Management - Monthly Fee',
            127,
            'Management of Funding for Supports',
            14,
            'Improved Life Choices',
            'MON',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_001_0118_1_3',
            'Early Childhood Intervention Professional - Psychologist',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_003_0118_1_3',
            'Early Childhood Intervention Professional - Physiotherapist',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_005_0118_1_3',
            'Early Childhood Intervention Professional - Other Early Childhood Professional',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_007_0118_1_3',
            'Early Childhood Intervention Professional - Therapy Assistant - Level 1',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_008_0118_1_3',
            'Early Childhood Intervention Professional - Therapy Assistant - Level 2',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_035_0106_1_3',
            'Assistance With Decision Making Daily Planning and Budgeting',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;