INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '05_120603831_0103_1_2',
            'Standing and/or Walking Frame - Child',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_120606096_0105_1_2',
            'Wheeled Walker - Standard',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_120606097_0105_1_2',
            'Rollator - Standard',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_120606811_0105_1_2',
            'Walking Frame or Walker',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_120606831_0105_1_2',
            'Rollator - Standard - Child',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_120612100_0105_1_2',
            'Walking Tables',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121205811_0109_1_2',
            'Vehicle Modification - Adaptions for Driver Control',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121208111_0109_1_2',
            'Vehicle Modification - Adaptions For Ancillary Functions e.g. Lights Locking',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121209821_0109_1_2',
            'Vehicle Modification - For Seating and/or Seat Belts',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121212811_0103_1_2',
            'Specialised Child Car Seats - no Vehicle Modification Required',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121215811_0109_1_2',
            'Vehicle Modification - Hoist for Passenger Loading (without Wheelchair)',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121218811_0109_1_2',
            'Vehicle Modification - Hoist for Occupied Wheelchair Loading',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121221811_0109_1_2',
            'Vehicle Modification - Hoist/Ramp for Unoccupied Wheelchair Loading',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121227121_0109_1_2',
            'Vehicle Modification - Chassis/Body work - For Wheelchair Passenger',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121227125_0108_1_2',
            'AT Rental - Vehicle modified for Access',
            108,
            'Assistance With Travel/Transport Arrangements',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121227221_0109_1_2',
            'Vehicle Modification - Chassis/Body work - For Wheelchair Seated Driver',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121230811_0109_1_2',
            'Vehicle Accessory -Trailer for wheeled mobility device',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121290111_0109_1_2',
            'Vehicle Modification - Engineers Certification',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121800821_0112_1_2',
            'Bicycle - Tricycle and/or Carts adapted for specific functional needs',
            112,
            'Assistive Equipment For Recreation',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121805111_0112_1_2',
            'Bicycle - Adapted FOR Hand Propulsion',
            112,
            'Assistive Equipment For Recreation',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_121821871_0112_1_2',
            'Bicycle - Adaptation for Pedals/Seat/Handle Bars',
            112,
            'Assistive Equipment For Recreation',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122203811_0105_1_2',
            'Wheelchair - Manual - Folding – Basic',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122203821_0105_1_2',
            'Wheelchair - Manual - Folding - Custom Made',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122203891_0105_1_2',
            'Wheelchair - Manual - Tilt In Space',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122203911_0105_1_2',
            'Wheelchair - Manual - Rigid Frame',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122218111_0105_1_2',
            'Wheelchair - Manual - Attendant Propel - Custom Folding/Rigid Frame',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122290811_0105_1_2',
            'Wheelchair - Manual - Sport and Recreation Use',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122303811_0105_1_2',
            'Scooter - Indoor/Outdoor use',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122303891_0105_1_2',
            'Scooter - Heavy Duty/Robust Activity Specific',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122303911_0105_1_2',
            'Scooter - Electric Powered – Portable',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122303991_0105_1_2',
            'Scooter - Small Folding/Travel Light-Weight',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122306139_0105_1_2',
            'Wheelchair - Powered - With Powered Standing Mechanism',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122306191_0105_1_2',
            'Wheelchair - Powered - All Terrain/Heavy Duty Base (WITHOUT Seating)',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122306811_0105_1_2',
            'Wheelchair - Powered Base with or without Tilt - Indoor/Outdoor use',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122306824_0105_1_2',
            'Wheelchair - Powered Base - Portable/Folding',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122403811_0105_1_2',
            'Wheelchair Accessory - Powered Alternate Operator Control System',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122409871_0105_1_2',
            'Wheelchair Accessory - Power-Assist Drive Technology',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122442871_0105_1_2',
            'Wheelchair Accessory - Health-Related AT/Ventilator Carrier',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122490811_0105_1_2',
            'Wheelchair Accessory - Powered Adjustment for Limbs or Recline orElevate',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122500821_0105_1_2',
            'Postural Support - Seating System - Custom Made',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122503111_0105_1_2',
            'Postural Support - Positioning - Back',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122506111_0105_1_2',
            'Postural Support - Positioning - Seat',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122524111_0105_1_2',
            'Postural Support - Wheelchair Accessory',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122524811_0105_1_2',
            'Postural Support - Seating Componentry and Accessories',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122707821_0105_1_2',
            'Stroller/Pram/Buggy with Specialised Seating system',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122707831_0105_1_2',
            'Stroller/Pram/Buggy/Push Chair with Supportive Seating',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122707931_0105_1_2',
            'Wheeled base - paediatric - height adaptable for seating',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_122715831_0105_1_2',
            'Crawlers/Mobility Boards/Trolley',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_123603811_0105_1_2',
            'Transfer AT - Mobile Hoist including Slings (x2)',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_123606868_0105_1_2',
            'Transfer AT - Mobile Hoist Seat or Table',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;