INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '01_700_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Psychologist',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_701_0128_1_3',
            'Assessment Recommendation Therapy or Training Supports - Psychologist',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_720_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Physiotherapist',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_721_0128_1_3',
            'Assessment Recommendation Therapy or Training Supports - Physiotherapist',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_740_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Other Professional',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_741_0128_1_3',
            'Assessment Recommendation Therapy or Training Supports - Other Professional',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_760_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Dietitian',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_760_0128_3_3',
            'Assessment Recommendation Therapy or Training Supports - Dietitian',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0102_1_1',
            'Provider travel - non-labour costs',
            102,
            'Assistance to Access and Maintain Employment or higher education',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0104_1_1',
            'Provider travel - non-labour costs',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0106_1_1',
            'Provider travel - non-labour costs',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0107_1_1',
            'Provider travel - non-labour costs',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0110_1_1',
            'Provider travel - non-labour costs',
            110,
            'Specialist Positive Behaviour Support',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0114_1_1',
            'Provider travel - non-labour costs',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0115_1_1',
            'Provider travel - non-labour costs',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0117_8_1',
            'Provider travel - non-labour costs',
            117,
            'Development Of Daily Living And Life Skills',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0118_1_1',
            'Provider travel - non-labour costs',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0119_1_1',
            'Provider travel - non-labour costs',
            119,
            'Specialised Hearing Services',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0120_1_1',
            'Provider travel - non-labour costs',
            120,
            'Household Tasks',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0126_1_1',
            'Provider travel - non-labour costs',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0128_1_1',
            'Provider travel - non-labour costs',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0129_1_1',
            'Provider travel - non-labour costs',
            129,
            'Specialised Driver Training',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0132_1_1',
            'Provider travel - non-labour costs',
            132,
            'Support Coordination',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0134_1_1',
            'Provider travel - non-labour costs',
            134,
            'Hearing Services',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_799_0135_1_1',
            'Provider travel - non-labour costs',
            135,
            'Customised Prosthetics (includes Orthotics)',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_801_0115_1_1',
            'Assistance in Supported Independent Living - Standard - Weekday Daytime',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_802_0115_1_1',
            'Assistance in Supported Independent Living - Standard - Weekday Evening',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_803_0115_1_1',
            'Assistance in Supported Independent Living - Standard - Weekday Night',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_804_0115_1_1',
            'Assistance in Supported Independent Living - Standard - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_805_0115_1_1',
            'Assistance in Supported Independent Living - Standard - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_806_0115_1_1',
            'Assistance in Supported Independent Living - Standard - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_811_0115_1_1',
            'Assistance in Supported Independent Living - High Intensity - Weekday Daytime',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_812_0115_1_1',
            'Assistance in Supported Independent Living - High Intensity - Weekday Evening',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_813_0115_1_1',
            'Assistance in Supported Independent Living - High Intensity - Weekday Night',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_814_0115_1_1',
            'Assistance in Supported Independent Living - High Intensity - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_815_0115_1_1',
            'Assistance in Supported Independent Living - High Intensity - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_816_0115_1_1',
            'Assistance in Supported Independent Living - High Intensity - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_821_0115_1_1',
            'Assistance in Supported Independent Living - Weekly',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'WK',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_822_0115_1_1',
            'Assistance in Supported Independent Living - Exit Accommodation Permanently',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'WK',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_832_0115_1_1',
            'Assistance in Supported Independent Living - Night-Time Sleepover',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_850_0106_1_1',
            'Individualised Living Options - Exploration and Design',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_851_0115_1_1',
            'Individualised Living Options - Support Model',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'WK',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '02_050_0108_1_1',
            'Specialised Transport To School/Educational Facility/Employment/Community',
            108,
            'Assistance With Travel/Transport Arrangements',
            2,
            'Transport',
            'D',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '02_051_0108_1_1',
            'Transport',
            108,
            'Assistance With Travel/Transport Arrangements',
            2,
            'Transport',
            'YR',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_040000111_0103_1_1',
            'Disability-Related Health Consumables - High Cost',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            TRUE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_040000919_0103_1_1',
            'Disability-Related Health Consumables - Low Cost',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_050903053_0103_1_1',
            'Incontinence Alarms',
            103,
            'Assistive Products For Personal Care And Safety',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_060000911_0135_1_1',
            'Low Cost AT - Prosthetics And Orthotics',
            135,
            'Customised Prosthetics (includes Orthotics)',
            3,
            'Consumables',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_089_0121_1_1',
            'Auslan Or Signed English Training',
            121,
            'Interpreting And Translation',
            3,
            'Consumables',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '03_090_0121_1_1',
            'Interpreting And Translating',
            121,
            'Interpreting And Translation',
            3,
            'Consumables',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;