INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '04_401_0104_1_1',
            'Access Community Social and Rec Activ - High Intensity - Weekday Evening',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_402_0104_1_1',
            'Access Community Social and Rec Activ - High Intensity - Saturday',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_403_0104_1_1',
            'Access Community Social and Rec Activ - High Intensity - Sunday',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_404_0104_1_1',
            'Access Community Social and Rec Activ - High Intensity - Public Holiday',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_450_0125_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Daytime',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_450_0136_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Daytime',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_451_0125_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Evening',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_451_0136_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Evening',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_452_0125_1_1',
            'Intensive and Complex Behaviour Supports - Saturday',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_452_0136_1_1',
            'Intensive and Complex Behaviour Supports - Saturday',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_453_0125_1_1',
            'Intensive and Complex Behaviour Supports - Sunday',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_453_0136_1_1',
            'Intensive and Complex Behaviour Supports - Sunday',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_454_0125_1_1',
            'Intensive and Complex Behaviour Supports - Public Holiday',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_454_0136_1_1',
            'Intensive and Complex Behaviour Supports - Public Holiday',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_590_0125_6_1',
            'Activity Based Transport',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_591_0136_6_1',
            'Activity Based Transport',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_592_0104_6_1',
            'Activity Based Transport',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_599_0104_6_1',
            'Centre Capital Cost',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_599_0133_5_1',
            'Centre Capital Cost',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_599_0136_6_1',
            'Centre Capital Cost',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_600_0104_6_1',
            'Group Activities - High Intensity - Weekday Daytime',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_601_0104_6_1',
            'Group Activities - High Intensity - Weekday Evening',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_602_0104_6_1',
            'Group Activities - High Intensity - Saturday',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_603_0104_6_1',
            'Group Activities - High Intensity - Sunday',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_604_0104_6_1',
            'Group Activities - High Intensity - Public Holiday',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_799_0104_6_1',
            'Provider travel - non-labour costs',
            104,
            'High Intensity Daily Personal Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_799_0125_6_1',
            'Provider travel - non-labour costs',
            125,
            'Participation In Community, Social And Civic Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_799_0133_5_1',
            'Provider travel - non-labour costs',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_799_0136_6_1',
            'Provider travel - non-labour costs',
            136,
            'Group And Centre Based Activities',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_801_0133_5_1',
            'Supports in Employment - Weekday Daytime',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_802_0133_5_1',
            'Supports in Employment - Weekday Evening',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_803_0133_5_1',
            'Supports in Employment - Saturday',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_804_0133_5_1',
            'Supports in Employment - Sunday',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_805_0133_5_1',
            'Supports in Employment - Public Holiday',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '04_821_0133_6_1',
            'Activity Based Transport',
            133,
            'Specialised Supported Employment',
            4,
            'Assistance with Social, Economic and Community Participation',
            'E',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0103_1_2',
            'AT Supplementary Charge - AT Personal Care/Safety',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0105_1_2',
            'AT Supplementary Charge - Personal Mobility or Transfer',
            105,
            'Personal Mobility Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0109_1_2',
            'AT Supplementary Charge - Vehicle modifications',
            109,
            'Vehicle Modifications',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0112_1_2',
            'AT Supplementary Charge - Recreation including sport',
            112,
            'Assistive Equipment For Recreation',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0113_1_2',
            'AT Supplementary Charge - Vision',
            113,
            'Vision Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0122_1_2',
            'AT Supplementary Charge - Hearing products',
            122,
            'Hearing Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0123_1_2',
            'AT Supplementary Charge - Household Tasks and Control',
            123,
            'Assistive Products For Household Tasks',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0124_1_2',
            'AT Supplementary Charge - Communication and Information support',
            124,
            'Communication And Information Equipment',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_0002_0135_1_2',
            'AT Supplementary Charge - Prosthesis or Orthosis',
            135,
            'Customised Prosthetics (includes Orthotics)',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040312115_0103_1_2',
            'AT Rental - Assistive Products for Respiration Support',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040312801_0103_1_1',
            'Ventilators - Supplemental Ventilation Support (including CPAP and BPAP)',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040312811_0103_1_1',
            'Ventilators - Invasive Ventilation for Continuous Use',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040313111_0103_1_1',
            'Ventilator accessory - Filters and/or Humidifiers',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040321811_0103_1_1',
            'Aspirators',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_040322811_0103_1_1',
            'Cough Assist Machine',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;