INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '01_404_0104_1_1',
            'Assistance With Self-Care Activities - High Intensity - Public Holiday',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_405_0104_1_1',
            'Assistance With Self-Care Activities - High Intensity - Weekday Night',
            104,
            'High Intensity Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_450_0107_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Daytime',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_450_0115_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Daytime',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_451_0107_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Evening',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_451_0115_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Evening',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_452_0107_1_1',
            'Intensive and Complex Behaviour Supports - Saturday',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_452_0115_1_1',
            'Intensive and Complex Behaviour Supports - Saturday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_453_0107_1_1',
            'Intensive and Complex Behaviour Supports - Sunday',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_453_0115_1_1',
            'Intensive and Complex Behaviour Supports - Sunday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_454_0107_1_1',
            'Intensive and Complex Behaviour Supports - Public Holiday',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_454_0115_1_1',
            'Intensive and Complex Behaviour Supports - Public Holiday',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_455_0107_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Night',
            107,
            'Daily Personal Activities',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_455_0115_1_1',
            'Intensive and Complex Behaviour Supports - Weekday Night',
            115,
            'Assistance With Daily Life Tasks In A Group Or Shared Living Arrangement',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_600_0114_1_1',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_601_0114_1_1',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_602_0114_1_1',
            'Delivery of Health Supports by an Enrolled Nurse - Saturday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_603_0114_1_1',
            'Delivery of Health Supports by an Enrolled Nurse - Sunday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_604_0114_1_1',
            'Delivery of Health Supports by an Enrolled Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_605_0114_1_1',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_606_0114_1_1',
            'Delivery of Health Supports by a Registered Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_607_0114_1_1',
            'Delivery of Health Supports by a Registered Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_608_0114_1_1',
            'Delivery of Health Supports by a Registered Nurse - Saturday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_609_0114_1_1',
            'Delivery of Health Supports by a Registered Nurse - Sunday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_610_0114_1_1',
            'Delivery of Health Supports by a Registered Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_611_0114_1_1',
            'Delivery of Health Supports by a Registered Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_612_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_613_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_614_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse - Saturday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_615_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse - Sunday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_616_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_617_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_618_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Daytime',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_619_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Evening',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_620_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Saturday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_621_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Sunday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_622_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Public Holiday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_623_0114_1_1',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Night',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_624_0114_1_1',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Daytime',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_625_0114_1_1',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Evening',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_626_0114_1_1',
            'Delivery of Health Supports by a Nurse Practitioner - Saturday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_627_0114_1_1',
            'Delivery of Health Supports by a Nurse Practitioner - Sunday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_628_0114_1_1',
            'Delivery of Health Supports by a Nurse Practitioner - Public Holiday',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_629_0114_1_1',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Night',
            114,
            'Community Nursing Care',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_650_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Occupational Therapist',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_653_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Speech Pathologist',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_661_0128_1_3',
            'Assessment Recommendation Therapy or Training Supports - Occupational Therapist',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_663_0118_1_3',
            'Assessment Recommendation Therapy or Training - EC - Podiatrist',
            118,
            'Early Intervention Supports For Early Childhood',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_663_0128_1_3',
            'Assessment Recommendation Therapy or Training Supports - Podiatrist',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '01_665_0128_1_3',
            'Assessment Recommendation Therapy or Training Supports - Speech Pathologist',
            128,
            'Therapeutic Supports',
            1,
            'Assistance with Daily Life (Includes SIL)',
            'H',
            FALSE,
            'Core',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;