INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '05_800188834_0103_1_2',
            'Early Childhood Flexible AT Package 1',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_800288834_0103_1_2',
            'Early Childhood Flexible AT Package 2',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_800388834_0103_1_2',
            'Early Childhood Flexible AT Package 3',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_801288834_0103_1_2',
            'Flexible AT Package - For Changing Need',
            103,
            'Assistive Products For Personal Care And Safety',
            5,
            'Assistive Technology',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '05_900101111_0130_1_2',
            'Assistance Animal - Dog Guide',
            130,
            'Assistance Animals',
            5,
            'Assistive Technology',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_123615401_0111_2_2',
            'HM - Ceiling Hoist',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_180000111_0111_2_2',
            'HM Rental - Bathroom Toilet Ramp',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182100401_0111_2_2',
            'MHM - Electrical and Door Automation',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182409401_0111_2_2',
            'MHM - External Door',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182409402_0111_2_2',
            'MHM - Internal Door',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182415401_0111_2_2',
            'MHM - Flooring',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182488377_0111_2_2',
            'HM - Bathroom/Toilet - Structural work',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182488378_0111_2_2',
            'HM - Kitchen or Laundry - Structural Work',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182490112_0111_2_2',
            'HM - Building Works Project Management',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495121_0111_2_2',
            'CHM - Deposit',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495221_0111_2_2',
            'CHM - Progress Stage',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495321_0111_2_2',
            'CHM - Practical Completion',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495322_0111_2_2',
            'MHM - Practical Completion',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495401_0111_2_2',
            'MHM - Bathroom',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495402_0111_2_2',
            'MHM - Kitchen',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495405_0111_2_2',
            'MHM - Laundry',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495407_0111_2_2',
            'MHM - Other works including Bedroom',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495413_0111_2_2',
            'MHM - Toilet Replacement',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495414_0111_2_2',
            'MHM - Cabinetry Alterations',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182495421_0111_2_2',
            'HM - Certification and Compliance Approval',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_182499311_0111_2_2',
            'HM - Design Consultation with Builder',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_183003384_0111_2_2',
            'HM - Elevator',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_183010387_0111_2_2',
            'HM - Stair Climber or Stair / Platform Lift',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_183018404_0111_2_2',
            'MHM - Ramp',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_183018405_0111_2_2',
            'HM - Ramp - Structural',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_183090401_0111_2_2',
            'MHM - Pathway - External',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_270303401_0111_2_2',
            'MHM - Airconditioning',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_431_0131_2_2',
            'Specialist Disability Accommodation (SDA) - Quotable Amount',
            131,
            'Specialised Disability Accommodation',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_432_0131_2_2',
            'SDA Vacancy - Person-Specific Adjustment',
            131,
            'Specialised Disability Accommodation',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            TRUE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_501824150_0111_2_2',
            'Building Modifications due to damage caused by disability-related behaviours',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '06_501824151_0111_2_2',
            'Building Modifications due to damage caused by AT',
            111,
            'Home Modification Design And Construction',
            6,
            'Home Modifications and Specialised Disability Accommodation (SDA)',
            'E',
            FALSE,
            'Capital',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_001_0106_8_3',
            'Support Coordination Level 1: Support Connection',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_002_0106_8_3',
            'Support Coordination Level 2: Coordination of Supports',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_004_0132_8_3',
            'Support Coordination Level 3: Specialist Support Coordination',
            132,
            'Support Coordination',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_101_0106_6_3',
            'Psychosocial Recovery Coaching - Weekday Daytime',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_102_0106_6_3',
            'Psychosocial Recovery Coaching - Weekday Evening',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_103_0106_6_3',
            'Psychosocial Recovery Coaching - Weekday Night',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_104_0106_6_3',
            'Psychosocial Recovery Coaching - Saturday',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_105_0106_6_3',
            'Psychosocial Recovery Coaching - Sunday',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_106_0106_6_3',
            'Psychosocial Recovery Coaching - Public Holiday',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_501_0106_6_3',
            'Activity Based Transport',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_799_0106_6_3',
            'Provider travel - non-labour costs',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            7,
            'Support Coordination',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_799_0117_8_3',
            'Provider travel - non-labour costs',
            117,
            'Development Of Daily Living And Life Skills',
            7,
            'Support Coordination',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '07_799_0132_8_3',
            'Provider travel - non-labour costs',
            132,
            'Support Coordination',
            7,
            'Support Coordination',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '08_005_0106_2_3',
            'Assistance With Accommodation And Tenancy Obligations',
            106,
            'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
            8,
            'Improved Living Arrangements',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;