INSERT INTO ndis_support_items (
        support_item_number, support_item_name, registration_group_number, registration_group_name,
        support_category_number, support_category_name, unit, quote_required, support_purpose,
        price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
        non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
    )
    VALUES
    (
            '15_037_0117_1_3',
            'Skill Development And Training including Public Transport Training',
            117,
            'Development Of Daily Living And Life Skills',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_038_0117_1_3',
            'Training For Carers/Parents',
            117,
            'Development Of Daily Living And Life Skills',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_043_0128_1_3',
            'Assessment Recommendation Therapy or Training - Counsellor',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_045_0128_1_3',
            'Community Engagement Assistance',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_046_0129_1_3',
            'Specialised Driver Training',
            129,
            'Specialised Driver Training',
            15,
            'Improved Daily Living Skills',
            'E',
            TRUE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_047_0135_1_3',
            'Selection And/or Manufacture Of Customised Or Wearable Technology',
            135,
            'Customised Prosthetics (includes Orthotics)',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_049_0128_1_3',
            'Multidisciplinary Team',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'E',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_052_0128_1_3',
            'Therapy Assistant - Level 1',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_053_0128_1_3',
            'Therapy Assistant - Level 2',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_054_0128_1_3',
            'Assessment Recommendation Therapy or Training - Psychologist',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_055_0128_1_3',
            'Assessment Recommendation Therapy or Training - Physiotherapist',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_056_0128_1_3',
            'Assessment Recommendation Therapy or Training - Other Professional',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_062_0118_1_3',
            'Early Childhood Intervention Professional - Dietitian',
            118,
            'Early Intervention Supports For Early Childhood',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_062_0128_3_3',
            'Assessment Recommendation Therapy or Training - Dietitian',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_200_0126_1_3',
            'Assessment Recommendation Therapy or Training - Exercise Physiologist',
            126,
            'Exercise Physiology & Personal Well-being Activities',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_200_0128_1_3',
            'Assessment Recommendation Therapy or Training - Exercise Physiologist',
            128,
            'Therapeutic Supports',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_300_0103_1_3',
            'Assistive Technology Mentoring',
            103,
            'Assistive Products For Personal Care And Safety',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_400_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_401_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_402_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_403_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_404_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_405_0114_1_3',
            'Delivery of Health Supports by an Enrolled Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_406_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_407_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_408_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_409_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_410_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_411_0114_1_3',
            'Delivery of Health Supports by a Registered Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_412_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_413_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_414_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_415_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_416_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_417_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_418_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_419_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_420_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_421_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_422_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_423_0114_1_3',
            'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_424_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Daytime',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_425_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Evening',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_426_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Saturday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_427_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Sunday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_428_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Public Holiday',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_429_0114_1_3',
            'Delivery of Health Supports by a Nurse Practitioner - Weekday Night',
            114,
            'Community Nursing Care',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_501_0119_1_3',
            'Provision of Hearing Services by an Audiologist',
            119,
            'Specialised Hearing Services',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_502_0134_1_3',
            'Provision of Hearing Services by an Audiologist',
            134,
            'Hearing Services',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        ),(
            '15_503_0134_1_3',
            'Provision of Hearing Services by an Audiometrist',
            134,
            'Hearing Services',
            15,
            'Improved Daily Living Skills',
            'H',
            FALSE,
            'Capacity Building',
            NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
            FALSE, FALSE, FALSE, FALSE, FALSE
        )
    ON CONFLICT (support_item_number) DO UPDATE SET
        support_item_name = EXCLUDED.support_item_name,
        registration_group_number = EXCLUDED.registration_group_number,
        registration_group_name = EXCLUDED.registration_group_name,
        support_category_number = EXCLUDED.support_category_number,
        support_category_name = EXCLUDED.support_category_name,
        unit = EXCLUDED.unit,
        quote_required = EXCLUDED.quote_required,
        support_purpose = EXCLUDED.support_purpose;