-- Import missing NDIS records (categories 9-15)
-- Generated from NDIS Support Catalogue 2025-26 v1.1

INSERT INTO ndis_support_items (
    support_item_number,
    support_item_name,
    registration_group_number,
    registration_group_name,
    support_category_number,
    support_category_name,
    unit,
    quote_required,
    support_purpose,
    price_act, price_nsw, price_nt, price_qld, price_sa, price_tas, price_vic, price_wa, price_remote, price_very_remote,
    non_face_to_face, provider_travel, short_notice_cancellations, ndia_requested_reports, irregular_sil_supports
)
VALUES
(
        '09_006_0106_6_3',
        'Life Transition Planning Incl. Mentoring Peer-Support And Indiv Skill Develop',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        9,
        'Increased Social and Community Participation',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_008_0116_6_3',
        'Innovative Community Participation',
        116,
        'Innovative Community Participation',
        9,
        'Increased Social and Community Participation',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_009_0117_6_3',
        'Skills Development And Training',
        117,
        'Development Of Daily Living And Life Skills',
        9,
        'Increased Social and Community Participation',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_011_0125_6_3',
        'Community Participation Activities',
        125,
        'Participation In Community, Social And Civic Activities',
        9,
        'Increased Social and Community Participation',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_590_0106_6_3',
        'Activity Based Transport',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        9,
        'Increased Social and Community Participation',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_591_0117_6_3',
        'Activity Based Transport',
        117,
        'Development Of Daily Living And Life Skills',
        9,
        'Increased Social and Community Participation',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_799_0106_6_3',
        'Provider travel - non-labour costs',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        9,
        'Increased Social and Community Participation',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '09_799_0117_6_3',
        'Provider travel - non-labour costs',
        117,
        'Development Of Daily Living And Life Skills',
        9,
        'Increased Social and Community Participation',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_002_0106_8_3',
        'Support Coordination Level 2: Coordination of Supports',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_011_0128_5_3',
        'Employment Related Assessment, Counselling and Advice  - Other Professional',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_016_0102_5_3',
        'Employment Assistance',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_021_0102_5_3',
        'School Leaver Employment Supports',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        10,
        'Finding and Keeping a Job',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_054_0128_5_3',
        'Employment Related  Assessment, Counselling and Advice - Psychologist',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_055_0128_5_3',
        'Employment Related  Assessment, Counselling and Advice - Physiotherapist',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_101_0106_6_3',
        'Psychosocial Recovery Coaching - Weekday Daytime',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_590_0102_5_3',
        'Activity Based Transport',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        10,
        'Finding and Keeping a Job',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_590_0133_5_3',
        'Activity Based Transport',
        133,
        'Specialised Supported Employment',
        10,
        'Finding and Keeping a Job',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_599_0133_5_3',
        'Centre Capital Cost',
        133,
        'Specialised Supported Employment',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_613_0128_5_3',
        'Employment Related  Assessment, Counselling and Advice - Developmental Educator',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_617_0128_5_3',
        'Employment Related  Assessment, Counselling and Advice - Occupational Therapist',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_620_0128_5_3',
        'Employment Related  Assessment, Counselling and Advice - Rehabilitation Counsellor',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_622_0128_5_3',
        'Employment Related  Assessment, Counselling and Advice - Speech Pathologist',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_799_0102_5_3',
        'Provider travel - non-labour costs',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        10,
        'Finding and Keeping a Job',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_799_0128_5_3',
        'Provider travel - non-labour costs',
        128,
        'Therapeutic Supports',
        10,
        'Finding and Keeping a Job',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_799_0133_5_3',
        'Provider travel - non-labour costs',
        133,
        'Specialised Supported Employment',
        10,
        'Finding and Keeping a Job',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '10_806_0133_5_1',
        'Supports in Employment - Weekday Daytime',
        133,
        'Specialised Supported Employment',
        10,
        'Finding and Keeping a Job',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '11_022_0110_7_3',
        'Specialist Behavioural Intervention Support',
        110,
        'Specialist Positive Behaviour Support',
        11,
        'Improved Relationships',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '11_023_0110_7_3',
        'Behaviour Management Plan Including Training in Behaviour Management Strategies',
        110,
        'Specialist Positive Behaviour Support',
        11,
        'Improved Relationships',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '11_024_0117_7_3',
        'Individual Social Skills Development',
        117,
        'Development Of Daily Living And Life Skills',
        11,
        'Improved Relationships',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '11_590_0117_7_3',
        'Activity Based Transport',
        117,
        'Development Of Daily Living And Life Skills',
        11,
        'Improved Relationships',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '11_799_0110_7_3',
        'Provider travel - non-labour costs',
        110,
        'Specialist Positive Behaviour Support',
        11,
        'Improved Relationships',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '11_799_0117_7_3',
        'Provider travel - non-labour costs',
        117,
        'Development Of Daily Living And Life Skills',
        11,
        'Improved Relationships',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '12_025_0128_3_3',
        'Advice provided by a Dietitian on managing diet for health and well-being',
        128,
        'Therapeutic Supports',
        12,
        'Improved Health and Wellbeing',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '12_027_0126_3_3',
        'Advice provided by an Exercise Physiologist regarding exercise required',
        126,
        'Exercise Physiology & Personal Well-being Activities',
        12,
        'Improved Health and Wellbeing',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '12_027_0128_3_3',
        'Advice provided by an Exercise Physiologist regarding exercise required',
        128,
        'Therapeutic Supports',
        12,
        'Improved Health and Wellbeing',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '12_029_0126_3_3',
        'Personal training provided by a Personal Trainer to a participant',
        126,
        'Exercise Physiology & Personal Well-being Activities',
        12,
        'Improved Health and Wellbeing',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '12_799_0126_3_3',
        'Provider travel - non-labour costs',
        126,
        'Exercise Physiology & Personal Well-being Activities',
        12,
        'Improved Health and Wellbeing',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '12_799_0128_3_3',
        'Provider travel - non-labour costs',
        128,
        'Therapeutic Supports',
        12,
        'Improved Health and Wellbeing',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '13_030_0102_4_3',
        'Transition Through School And To Further Education',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        13,
        'Improved Learning',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '13_590_0102_4_3',
        'Activity Based Transport',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        13,
        'Improved Learning',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '13_799_0102_4_3',
        'Provider travel - non-labour costs',
        102,
        'Assistance to Access and Maintain Employment or higher education',
        13,
        'Improved Learning',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '14_034_0127_8_3',
        'Plan Management - Monthly Fee',
        127,
        'Management of Funding for Supports',
        14,
        'Improved Life Choices',
        'MON',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_001_0118_1_3',
        'Early Childhood Intervention Professional - Psychologist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_003_0118_1_3',
        'Early Childhood Intervention Professional - Physiotherapist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_005_0118_1_3',
        'Early Childhood Intervention Professional - Other Early Childhood Professional',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_007_0118_1_3',
        'Early Childhood Intervention Professional - Therapy Assistant - Level 1',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_008_0118_1_3',
        'Early Childhood Intervention Professional - Therapy Assistant - Level 2',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_035_0106_1_3',
        'Assistance With Decision Making Daily Planning and Budgeting',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_037_0117_1_3',
        'Skill Development And Training including Public Transport Training',
        117,
        'Development Of Daily Living And Life Skills',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_038_0117_1_3',
        'Training For Carers/Parents',
        117,
        'Development Of Daily Living And Life Skills',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_043_0128_1_3',
        'Assessment Recommendation Therapy or Training - Counsellor',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_045_0128_1_3',
        'Community Engagement Assistance',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_046_0129_1_3',
        'Specialised Driver Training',
        129,
        'Specialised Driver Training',
        15,
        'Improved Daily Living Skills',
        'E',
        TRUE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_047_0135_1_3',
        'Selection And/or Manufacture Of Customised Or Wearable Technology',
        135,
        'Customised Prosthetics (includes Orthotics)',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_049_0128_1_3',
        'Multidisciplinary Team',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_052_0128_1_3',
        'Therapy Assistant - Level 1',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_053_0128_1_3',
        'Therapy Assistant - Level 2',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_054_0128_1_3',
        'Assessment Recommendation Therapy or Training - Psychologist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_055_0128_1_3',
        'Assessment Recommendation Therapy or Training - Physiotherapist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_056_0128_1_3',
        'Assessment Recommendation Therapy or Training - Other Professional',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_062_0118_1_3',
        'Early Childhood Intervention Professional - Dietitian',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_062_0128_3_3',
        'Assessment Recommendation Therapy or Training - Dietitian',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_200_0126_1_3',
        'Assessment Recommendation Therapy or Training - Exercise Physiologist',
        126,
        'Exercise Physiology & Personal Well-being Activities',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_200_0128_1_3',
        'Assessment Recommendation Therapy or Training - Exercise Physiologist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_300_0103_1_3',
        'Assistive Technology Mentoring',
        103,
        'Assistive Products For Personal Care And Safety',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_400_0114_1_3',
        'Delivery of Health Supports by an Enrolled Nurse - Weekday Daytime',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_401_0114_1_3',
        'Delivery of Health Supports by an Enrolled Nurse - Weekday Evening',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_402_0114_1_3',
        'Delivery of Health Supports by an Enrolled Nurse - Saturday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_403_0114_1_3',
        'Delivery of Health Supports by an Enrolled Nurse - Sunday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_404_0114_1_3',
        'Delivery of Health Supports by an Enrolled Nurse - Public Holiday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_405_0114_1_3',
        'Delivery of Health Supports by an Enrolled Nurse - Weekday Night',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_406_0114_1_3',
        'Delivery of Health Supports by a Registered Nurse - Weekday Daytime',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_407_0114_1_3',
        'Delivery of Health Supports by a Registered Nurse - Weekday Evening',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_408_0114_1_3',
        'Delivery of Health Supports by a Registered Nurse - Saturday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_409_0114_1_3',
        'Delivery of Health Supports by a Registered Nurse - Sunday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_410_0114_1_3',
        'Delivery of Health Supports by a Registered Nurse - Public Holiday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_411_0114_1_3',
        'Delivery of Health Supports by a Registered Nurse - Weekday Night',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_412_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse - Weekday Daytime',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_413_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse - Weekday Evening',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_414_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse - Saturday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_415_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse - Sunday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_416_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse - Public Holiday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_417_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse - Weekday Night',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_418_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Daytime',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_419_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Evening',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_420_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse Consultant - Saturday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_421_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse Consultant - Sunday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_422_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse Consultant - Public Holiday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_423_0114_1_3',
        'Delivery of Health Supports by a Clinical Nurse Consultant - Weekday Night',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_424_0114_1_3',
        'Delivery of Health Supports by a Nurse Practitioner - Weekday Daytime',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_425_0114_1_3',
        'Delivery of Health Supports by a Nurse Practitioner - Weekday Evening',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_426_0114_1_3',
        'Delivery of Health Supports by a Nurse Practitioner - Saturday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_427_0114_1_3',
        'Delivery of Health Supports by a Nurse Practitioner - Sunday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_428_0114_1_3',
        'Delivery of Health Supports by a Nurse Practitioner - Public Holiday',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_429_0114_1_3',
        'Delivery of Health Supports by a Nurse Practitioner - Weekday Night',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_501_0119_1_3',
        'Provision of Hearing Services by an Audiologist',
        119,
        'Specialised Hearing Services',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_502_0134_1_3',
        'Provision of Hearing Services by an Audiologist',
        134,
        'Hearing Services',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_503_0134_1_3',
        'Provision of Hearing Services by an Audiometrist',
        134,
        'Hearing Services',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_606_0118_1_3',
        'Early Childhood Intervention Professional - Counsellor',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_609_0118_1_3',
        'Early Childhood Intervention Professional - Exercise Physiologist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_610_0118_1_3',
        'Early Childhood Intervention Professional - Art Therapist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_610_0118_1_3',
        'Early Childhood Intervention Professional - Art Therapist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_610_0128_1_3',
        'Assessment Recommendation Therapy or Training - Art Therapist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_610_0128_1_3',
        'Assessment Recommendation Therapy or Training - Art Therapist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_611_0128_1_3',
        'Assessment Recommendation Therapy or Training - Audiologist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_613_0118_1_3',
        'Early Childhood Intervention Professional - Developmental educator',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_613_0128_1_3',
        'Assessment Recommendation Therapy or Training - Developmental Educator',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_615_0118_1_3',
        'Early Childhood Intervention Professional - Music Therapist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_615_0118_1_3',
        'Early Childhood Intervention Professional - Music Therapist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_615_0128_1_3',
        'Assessment Recommendation Therapy or Training - Music Therapist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_615_0128_1_3',
        'Assessment Recommendation Therapy or Training - Music Therapist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_617_0118_1_3',
        'Early Childhood Intervention Professional - Occupational Therapist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_617_0128_1_3',
        'Assessment Recommendation Therapy or Training - Occupational Therapist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_618_0128_1_3',
        'Assessment Recommendation Therapy or Training - Orthoptist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_619_0118_1_3',
        'Early Childhood Intervention Professional - Podiatrist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_619_0128_1_3',
        'Assessment Recommendation Therapy or Training - Podiatrist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_620_0128_1_3',
        'Assessment Recommendation Therapy or Training - Rehabilitation Counsellor',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_621_0118_1_3',
        'Early Childhood Intervention Professional - Social worker',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_621_0128_1_3',
        'Assessment Recommendation Therapy or Training - Social Worker',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_622_0118_1_3',
        'Early Childhood Intervention Professional - Speech Pathologist',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_622_0128_1_3',
        'Assessment Recommendation Therapy or Training - Speech Pathologist',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_625_0118_1_3',
        'Early Childhood Intervention Professional - Early Childhood Teacher or Educator',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'H',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0103_6_3',
        'Provider travel - non-labour costs',
        103,
        'Assistive Products For Personal Care And Safety',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0106_1_3',
        'Provider travel - non-labour costs',
        106,
        'Assistance In Coordinating Or Managing Life Stages, Transitions And Supports',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0114_1_3',
        'Provider travel - non-labour costs',
        114,
        'Community Nursing Care',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0117_1_3',
        'Provider travel - non-labour costs',
        117,
        'Development Of Daily Living And Life Skills',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0118_1_3',
        'Provider travel - non-labour costs',
        118,
        'Early Intervention Supports For Early Childhood',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0119_1_3',
        'Provider travel - non-labour costs',
        119,
        'Specialised Hearing Services',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0126_1_3',
        'Provider travel - non-labour costs',
        126,
        'Exercise Physiology & Personal Well-being Activities',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0128_1_3',
        'Provider travel - non-labour costs',
        128,
        'Therapeutic Supports',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0134_1_3',
        'Provider travel - non-labour costs',
        134,
        'Hearing Services',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        '15_799_0135_1_3',
        'Provider travel - non-labour costs',
        135,
        'Customised Prosthetics (includes Orthotics)',
        15,
        'Improved Daily Living Skills',
        'E',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    ),(
        'Bereavement',
        'Plan Management - Bereavement Payment',
        127,
        'Management of Funding for Supports',
        14,
        'Improved Life Choices',
        'MON',
        FALSE,
        'Capacity Building',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        FALSE, FALSE, FALSE, FALSE, FALSE
    )
ON CONFLICT (support_item_number) DO UPDATE SET
    support_item_name = EXCLUDED.support_item_name,
    registration_group_number = EXCLUDED.registration_group_number,
    registration_group_name = EXCLUDED.registration_group_name,
    support_category_number = EXCLUDED.support_category_number,
    support_category_name = EXCLUDED.support_category_name,
    unit = EXCLUDED.unit,
    quote_required = EXCLUDED.quote_required,
    support_purpose = EXCLUDED.support_purpose;
